### ISSUE TITLE
Support oneof fields

### ISSUE THREAD

**Issue by brendan-ward** [mafintosh/protocol-buffers#16]
Are you open to adding support for [oneof fields](https://developers.google.com/protocol-buffers/docs/proto#oneof)?

We have a case where we have property values that may be any one (and only one) of the basic types (string, int64, etc).  It looks like ```oneof``` would handle this case better.

If you are open to it, I could try to pull together a pull request to add this, but arguably I'm not that proficient at node yet so I'm a bit concerned about the performance impacts of anything I come up with.

**Comment by kevincennis** [comment]
Not to come in and just "+1" this, but for whatever it's worth, those commits from @brendan-ward look good to me. Would love to see a PR.

If there's anything I can do to help, please let me know.

**Comment by brendan-ward** [comment]
I was holding back a PR on this one while waiting for resolution of #21.  I could push this through without those changes, but since there was some overlap of defaults w/ how we were handling things in ```oneof``` fields.

@mafintosh do you want me to do a PR for this separate from updating defaults as per #21?

**Comment by mafintosh** [comment]
@brendan-ward that would be great.
