### ISSUE TITLE
Please support newer versions of node-gyp/io.js

### ISSUE THREAD

**Issue by MarkSwanson** [mafintosh/protocol-buffers#29]
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  c++ '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/Users/maswanso/.node-gyp/1.0.4/src -I/Users/maswanso/.node-gyp/1.0.4/deps/uv/include -I/Users/maswanso/.node-gyp/1.0.4/deps/v8/include -I../node_modules/nan  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -stdlib=libc++ -I/usr/local/include -MMD -MF ./Release/.deps/Release/obj.target/protobuf/src/init.o.d.raw  -c -o Release/obj.target/protobuf/src/init.o ../src/init.cpp
In file included from ../src/init.cpp:1:
In file included from ../src/common.h:7:
../node_modules/nan/nan.h:1848:10: error: no matching function for call to 'Encode'
  return node::Encode(
         ^~~~~~~~~~~~

Thanks.

**Comment by mafintosh** [comment]
This module is completely written in js and doesn't need compilation. Did you mean to create the issue here, https://github.com/chrisdew/protobuf?

**Comment by MarkSwanson** [comment]
Terribly sorry, I have failed at reading comprehension today.
Closing.
