### ISSUE TITLE
.proto files that use 0x values

### ISSUE THREAD

**Issue by tcave** [mafintosh/protocol-buffers#32]
Although the .proto language guide (https://developers.google.com/protocol-buffers/docs/proto) does not mention the use of *0x* the proto-c and proto-java compilers support this. So the enum definition below works with proto-c and proto-java compilers:

```
enum foo_t
{
  BAR_0 = 0x00;
  BAR_1 = 0x01;
  BAR_2 = 0x02;
}
```

However this fails with protocol-buffers.js with an error like:

```
undefined:4
al !== 0 && val !== 0 && val !== 0 && val !== 0 && val !== 0) throw new Error(
                                                                    ^
Error: Invalid enum value: 41
```

Certainly this should be considered a bug with a .proto file using this syntax, but I thought I would raise it here to save others spending time debugging this.

Regards, TC.

**Comment by mafintosh** [comment]
2.5.1 now supports hex notation. Thanks for reporting this.
