### ISSUE TITLE
Error: Groups are not supported

### ISSUE THREAD

**Issue by oncletom** [mafintosh/protocol-buffers#44]
Hello,

I have the following proto definition:

```
syntax = "proto2";

message TldMap {
  map<string, Tld> tlds = 1;
}

message Tld {
  repeated string rules = 1;
}
```

Which corresponds to that if I understand well:

```json
{
  "tlds": {
    "ac": ["com", "edu", "gov", "net"],
    "ad": [],
    "ae": [],
    "...": ["..."]
  }
}
```

When I try to decode an encoded data buffer, it throws the aforementioned error ``:

```js
var schema = protobuf(fs.readFileSync('./rules.proto'));
var buf = fs.readFileSync('./rules');

var data = schema.TldMap.decode(buf);
```

Am I doing anything the wrong way? I cannot see how I use Groups here.

Thanks :-)

**Comment by oncletom** [comment]
cc @DavidBruant

**Comment by mafintosh** [comment]
Did you encode the buffer using this module or another one? And if you used
another module could you share the rules file somewhere?

**Comment by oncletom** [comment]
Nah I encoded the data with the same module, with a fresh install of today.

Anything I can do to help you find where the problem lies?

**Comment by mafintosh** [comment]
If you can create a simple failing test case and open a pr that would be
great

**Comment by oncletom** [comment]
:+1: will do, great idea :-)

**Comment by oncletom** [comment]
Well, by creating the test case it happened to work. I tried again in my project and it did too.
Maybe I misused the lib at some point without noticing it.

Thanks for your support, great job! :-)

**Comment by mikeal** [comment]
I think this is happening if you have a mid-write failure. I'm seeing this after a recent crash.
