### ISSUE TITLE
encode int64 error

### ISSUE THREAD

**Issue by rpdg** [mafintosh/protocol-buffers#48]
proto:
message ProtobufModelDto {
	required int64 Id =1;
}

js:
     var obj1 = {
		Id: : 9999999999999999
	};

	var str = schema.ProtobufModelDto.encode(obj1);
	var obj = schema.ProtobufModelDto.decode(str);

console.log( obj.Id );

**Comment by mafintosh** [comment]
this is because your id number is too large to be represented in javascript. just try opening a node repl and do

```
node
> 9999999999999999
10000000000000000
```

hopefully this will be fixed in future version of js
