### ISSUE TITLE
Binary response data from service throws exception during deserilizing.

### ISSUE THREAD

**Issue by arpanmukherjee1** [mafintosh/protocol-buffers#50]
@mafintosh 

Below is the `.proto` file and the data file attached.
```
message GenericTable {
  required Header header = 1;  
  optional Table data = 2;
  optional bytes compresseddata = 3;
  message Header{
			required double version=1;
			required bool iscompressed=2;
			required string schema=3;
			required string exception=4;
  }

  message Table{
			repeated Row rows=1;
  }

  message Row{
			repeated Cell cells=1;
  }

  message  Cell{
			optional string primitiveString=1;
			optional int64  primitiveLong=2;
			optional int32 primitiveInt=3;
			optional double primitiveDouble=4;
			optional bool primitiveBool=5;
			optional int64 primitiveDate=6;
			optional Row complexValue=7;
			optional Table listValue=8;
  }

}
```

[data.txt](https://github.com/mafintosh/protocol-buffers/files/47311/data.txt)

The hex data is not encoded by protocol-buffers but given by an external service.

We are not able to de-serialize the proto binary data (attached).

The error message we are getting when running the decode is following:
*Groups are not supported.*

**Comment by mafintosh** [comment]
are you sure the data is encoded using the same schema? that error usually means that something is wrong with the encoded message

**Comment by arpanmukherjee1** [comment]
We got this working. There was an issue with the data.

Thanks
