### ISSUE TITLE
decodeDelimited

### ISSUE THREAD

**Issue by eapikat** [mafintosh/protocol-buffers#57]
Does this exist?

**Comment by mafintosh** [comment]
what would it do?

**Comment by eapikat** [comment]
There are some messages that are delimited by a Varint32 which specifies the length of the next message. It would continue to return the messages until end. So, for example, the message has 6 messages inside it. If the first one is length 80, then the varint32 read will determine that, and also know that 80 was represented in 1 byte. So it would read pos 1 to 80 for the message. The next call to the buffer would read the varint32 again, which, for example might be length of 160. That would then also know that it takes 2 bytes to represent that. So the next message is from position 83 to 242. Alternatively, it could return an array of all the messages in the buffer, but it would still have to go through this exercise.

**Comment by eapikat** [comment]
It's in the Java API, more info here: http://stackoverflow.com/questions/2340730/are-there-c-equivalents-for-the-protocol-buffers-delimited-i-o-functions-in-ja

And it's in decodeIO so unfortunately, a lot of people have started to use it, and it's become a defacto standard for delimiting protobuf messages. I think ...

**Comment by mafintosh** [comment]
Ah ok. No there aren't any plans to include that api here. You could do that yourself though using the `.bytes` property

``` js
var offset = 0
messages.SomeMessage.decode(bigBuffer, offset)
console.log('consumed bytes:', messages.SomeMessage.decode.bytes) 
offset += messages.SomeMessage.decode.bytes
messages.SomeMessage.decode(bigBuffer, offset)
console.log('consumed bytes:', messages.SomeMessage.decode.bytes) 
```

**Comment by mafintosh** [comment]
I personally use https://github.com/mafintosh/length-prefixed-stream all the time as well to length prefix messages over an io stream also. I can link you some examples if you're interested.
