### ISSUE TITLE
decoding a corrupt message puts decode into an infinite loop

### ISSUE THREAD

**Issue by killerstorm** [mafintosh/protocol-buffers#66]
Example:

```
 var pb = require('protocol-buffer')
 var m = pb("message Test1 { required int32 a = 1; }")
 console.log(m.Test1.decode(new Buffer([0x08, 0x80, 0x80, 0x80, 0x80])))
```

m.Test1.decode doesn't return (infinite loop?)

**Comment by mafintosh** [comment]
returns `{a: undefined}` when i run it on my machine (which is still wrong, it should throw). are you sure you are using the latest version?

**Comment by mafintosh** [comment]
fixed in latest version

**Comment by mafintosh** [comment]
(if for some reason that isn't the case please re-open)
