### ISSUE TITLE
Could not decode varint at Validator.deserializeOpenToken

### ISSUE THREAD

**Issue by hemanjayam** [mafintosh/protocol-buffers#69]
Hi,
As the older version(2.6.1) of protocol-buffers was causing problem with node 6.9.5, I upgraded module to 3.2.1. From then on I am getting error "Could not decode varint at Validator.deserializeOpenToken", I am not sure what exactly the cause is. Can someone help me in understanding what might have caused this issue, is it due to upgradation of module or node version.

It used to work properly with protocol-buffer(2.6.1) and node 0.12 combination

**Comment by mafintosh** [comment]
I think you meant to open this on another repo

**Comment by hemanjayam** [comment]
It seems the issue was due to updated buffer module with node version. It got fixed after checking and fixing length of buffer. Thanks for help
