### ISSUE TITLE
Cli tool generates wrong enum encoding

### ISSUE THREAD

**Issue by vkosh** [mafintosh/protocol-buffers#74]
It looks like enum generation is broken in the cli tool. The "enc" array in generated code contains "undefined" for enum, which leads to errors like "TypeError: Cannot read property 'encodingLength' of undefined".
See https://gist.github.com/vkosh/d8bc50fd17cad8e51e9c2b8725655017#file-test-proto-js-L32

**Comment by mafintosh** [comment]
Thanks for the issue. I'll see if we can make an easy fix for that :)
